config/routes.rb
CherryTree::Application.routes.draw do

	root :to => "site#index"
	
	resources :activities do
		resources :comments
	end
	
	resources :articles do
		resources :comments
	end
	
	resources :awards do
		get 'admin', :on => :collection
		get 'unlock', :on => :member
		get 'earned', :on => :collection
		get 'set', :on => :collection
		get 'print', :on => :member
	end
	
	resources :blog do
		get	:admin, :on => :collection
	end
	
	resources :checkins do
		post 'pokki_create', :on => :collection
	end
	
	resources :lessons do
		resources :screens
	end
	
	resources :children do
		get 'login', :on => :collection
		get 'home', :on => :collection
		get 'profile', :on => :member
		post 'give_cherries', :on => :member
				
		resources :approvals

		resources :objective_assignments do
			get 'pokki', :on => :collection
		end
		
		resources :award_assignments do
			post 'amzn', :on => :collection
		end
		resources :lesson_assignments
		resources :lessons
		
		resources :journal_entries do
			resources :comments
			get 'customize', :on => :member
		end
		resources :invitations
		
		resources :supporters do
			get 'disable', :on => :collection
			get 'enable', :on => :collection
		end
	end

	resources :contacts do
		get 'admin', :on  => :collection
	end
	
	resources :forums do
		resources :topics do
			resources :posts
		end
	end
	
	resources :games
	
	resources :guides
	
	resources :invitations

	resources :merches
	
	resources :store
	
	resources :notes do
		get 'archive', :on => :collection
		get 'customize', :on => :member
	end
	
	resources :objectives 
		
	resources :products
	
	resources :quizzes do
		get 'admin', :on => :collection
		get 'inspect', :on => :member
		get 'recap', :on => :member
		resources :questions do
			get 'admin', :on => :collection
			post 'answer', :on => :member
			resources :answers do
				get 'admin', :on => :collection
			end
		end
	end
	
	resources :relations
	
	resources :sessions do
		collection do
			get 'pending'
			get 'register'
			get 'register_invitee'
			post 'go_facebook'
			post 'go_site_facebook'
			get 'ret_facebook'
			get 'ret_site_facebook'
			post 'go_twitter'
			post 'go_site_twitter'
			get 'ret_twitter'
			get 'ret_site_twitter'
			post 'json_create'
		end
	end
	
	resources :static_pages do
		get 'admin', :on => :collection
	end
	
	resources :page_elements do
		get 'update_pos', :on => :member
		get 'update_width', :on => :member
	end
	
	resources :resources
	
	resources  :users do
		post 'collect_email', :on => :collection
		get 'resend', :on => :member
		get 'settings', :on => :collection
		get 'home', :on => :collection
		post 'invite', :on => :collection
		resources :photos
	end
	
	resources :weekly_approvals
	
	resources :wishlist_items
	
	match '/update_page/:obj_type/:obj_id', :to => 'page_elements#updater'
	
	# for award_assignments ajax
	match 'activate/award/:award_id/for/:child_id', :to => 'award_assignments#activate'
	match 'deactivate/award/assignment/:assignment_id/for/:child_id', :to => 'award_assignments#deactivate'
	match 'update/award/assignment/:assignment_id/for/:child_id', :to => 'award_assignments#update'
	
	# for objective_assignments ajax
	match 'activate/objective/:objective_id/for/:child_id', :to => 'objective_assignments#activate'
	match 'deactivate/objective/assignment/:assignment_id/for/:child_id', :to => 'objective_assignments#deactivate'
	match 'update/objective/assignment/:assignment_id/for/:child_id', :to => 'objective_assignments#update'

	# for lesson_assignments ajax
	match 'update/lesson/assignment/:lesson_id/for/:child_id', :to => 'lesson_assignments#update'


	match 'requested/objective/:objective_id/for/:child_id', :to => 'objective_assignments#requested'
	match 'unrequested/objective/assignment/:assignment_id/for/:child_id', :to => 'objective_assignments#unrequested'
	
	match 'require_confirmation/assignment/:assignment_id/for/:child_id', :to => 'objective_assignments#require_confirmation'
	match 'remove_confirmation/assignment/:assignment_id/for/:child_id',  :to => 'objective_assignments#remove_confirmation'
	
	match 'check_name/:name', :to => 'users#check_name'
	
	match '/admin/' => 'admin#index', :as => :admin_index

	match '/blog/archive/(:year/(:month))', :to => 'blog#index'
	
	match '/forgot' => 'users#forgot_password', :as => 'forgot'
	
	match '/home' => 'users#home', :as => 'home'
	match '/invitation/:code' => 'invitations#accept_invite', :as => 'invitation'
	match '/logout' => 'sessions#destroy', :as => 'logout'
	match '/login' => 'sessions#new', :as => 'login'
	match '/register' => 'sessions#register', :as => 'register'
	match '/reset' => 'users#reset_password', :as => 'reset'
	match '/activate/:token' => 'users#activate', :as => 'activate'
	match '/resend' => 'users#resend', :as => 'resend'
	match '/amazon/(:index/(:term))' => 'amazon#search', :as => 'amazon'
	match "/:permalink", :to => 'static_pages#show'
	
	
	
end

app/views/adult/_nav.html.haml
.tab_bar
	%ul
		- if current_page?( home_path )
			%li.home.selected
				= image_tag( 'home.png', :width => 25 )
				Home
		- else
			%li.home
				= link_to image_tag( 'home.png', :width => 25 ), home_path
				= link_to "Home", home_path
		- for child in @current_user.children
			- if @child.present? && child == @child
				%li.selected
					%a{ :href => child_path( child ) }
						= avatar_tag( child, :thumb, :width => 25 )
						= child.display_name
			- else
				%li
					%a{ :href => child_path( child ) }
						= avatar_tag( child, :thumb, :width => 25 )
						= child.display_name
		- for child in @current_user.supported_children
			- if @child.present? && child == @child
				%li.selected
					%a{ :href => child_path( child ) }
						= avatar_tag( child, :thumb, :width => 25 )
						= child.display_name
			- else
				%li
					%a{ :href => child_path( child ) }
						= avatar_tag( child, :thumb, :width => 25 )
						= child.display_name
		- if current_page?( new_child_path )
			%li.selected.add
				// = image_tag 'add.png', :width => 20
				Add Child
		- else
			%li.add
				%a{ :href => new_child_path }
					//= image_tag 'add.png', :width => 20
					Add Child

-#
	#main-nav
		%ul.navbar
			%li.more
				= link_to "Children", home_path
				%ul
					- unless @current_user.children.empty?
						- for child in @current_user.children
							%li
								= link_to child.display_name, child
					%li
						= link_to '+ Add Child', new_child_path
		
	
			- unless @current_user.supported_children.empty?
				%li.more
					= link_to "Supported Children", ""
					%ul
						- for child in @current_user.supported_children
							%li
								= link_to child.display_name, child
		
			%li.more
				= link_to "Notes", notes_path
				%ul
					%li
						= link_to 'Unread', notes_path
					%li
						= link_to 'All', archive_notes_path
			%li= link_to "Settings", settings_users_path

app/views/adult/home.html.haml
-# Used to show Children Dashboard to Parent
.child_profile.clearfix.parent_home
	/ = render @activities if @activities.present?
	#main-col
		.message
			%p Dear Parents
			%p.indent 
				Welcome to theCherryTree!  We are thrilled to have you here! 
			%p
				The CherryTree was created by child development experts, and parents just like you, to help with a problem we are all facing … how do we shape our children’s behavior and teach them important life skills in today's busy and distracted digital age?
			%p
				The CherryTree's incentive-based system lets you leverage technology in the parenting process.  There are lots of games and resources out there that focus on academic development, but the CherryTree will help you nurture your whole child. 
			%p
				You can set goals and assign fun activities that focus on (1) behavior and independence, (2) social and emotional well-being, (3) academics and school readiness, and (4) health and fitness. 
			%p
				As the CherryTree continues to grow, we hope to offer even more resources for parents, and even more fun things for kids to do and learn through our site.  Please reach out with any suggestions - we love feedback! 
			%p
				Warmly,
				%br
				The CherryTree Team
	#market.boxes
		%p
			Check out the cherryTree Market for toys, books and other materials to help your whole child grow.
		= link_to "Enter Store", "/store", :class => 'button_flat big'
		= link_to image_tag( 'market-small.png'), "/store", :class => 'market'
	#resources.boxes
		%p
			Visit our Parent Resources section for great parenting advice and information.
		= link_to "Go", resources_path, :class => 'button_flat big'
	-#
		faq.boxes
		%p
			Need some help with setting up goals and rewards? Check out these.
		= link_to "FAQ", "/faq", :class => 'button_flat big'