config/routes.rb
CherryTree::Application.routes.draw do

	root :to => "site#index"
	
	resources :activities do
		resources :comments
	end
	
	resources :articles do
		resources :comments
	end
	
	resources :awards do
		get 'admin', :on => :collection
		get 'unlock', :on => :member
		get 'earned', :on => :collection
		get 'set', :on => :collection
		get 'print', :on => :member
	end
	
	resources :blog do
		get	:admin, :on => :collection
	end
	
	resources :checkins do
		post 'pokki_create', :on => :collection
	end
	
	resources :lessons do
		resources :screens
	end
	
	resources :children do
		get 'login', :on => :collection
		get 'home', :on => :collection
		get 'profile', :on => :member
		post 'give_cherries', :on => :member
				
		resources :approvals

		resources :objective_assignments do
			get 'pokki', :on => :collection
		end
		
		resources :award_assignments do
			post 'amzn', :on => :collection
		end
		resources :lesson_assignments
		resources :lessons
		
		resources :journal_entries do
			resources :comments
			get 'customize', :on => :member
		end
		resources :invitations
		
		resources :supporters do
			get 'disable', :on => :collection
			get 'enable', :on => :collection
		end
	end

	resources :contacts do
		get 'admin', :on  => :collection
	end
	
	resources :forums do
		resources :topics do
			resources :posts
		end
	end
	
	resources :games
	
	resources :guides
	
	resources :invitations

	resources :merches
	
	resources :store
	
	resources :notes do
		get 'archive', :on => :collection
		get 'customize', :on => :member
	end
	
	resources :objectives 
		
	resources :products
	
	resources :quizzes do
		get 'admin', :on => :collection
		get 'inspect', :on => :member
		get 'recap', :on => :member
		resources :questions do
			get 'admin', :on => :collection
			post 'answer', :on => :member
			resources :answers do
				get 'admin', :on => :collection
			end
		end
	end
	
	resources :relations
	
	resources :sessions do
		collection do
			get 'pending'
			get 'register'
			get 'register_invitee'
			post 'go_facebook'
			post 'go_site_facebook'
			get 'ret_facebook'
			get 'ret_site_facebook'
			post 'go_twitter'
			post 'go_site_twitter'
			get 'ret_twitter'
			get 'ret_site_twitter'
			post 'json_create'
		end
	end
	
	resources :static_pages do
		get 'admin', :on => :collection
	end
	
	resources :page_elements do
		get 'update_pos', :on => :member
		get 'update_width', :on => :member
	end
	
	resources :resources
	
	resources  :users do
		post 'collect_email', :on => :collection
		get 'resend', :on => :member
		get 'settings', :on => :collection
		get 'home', :on => :collection
		post 'invite', :on => :collection
		resources :photos
	end
	
	resources :weekly_approvals
	
	resources :wishlist_items
	
	match '/update_page/:obj_type/:obj_id', :to => 'page_elements#updater'
	
	# for award_assignments ajax
	match 'activate/award/:award_id/for/:child_id', :to => 'award_assignments#activate'
	match 'deactivate/award/assignment/:assignment_id/for/:child_id', :to => 'award_assignments#deactivate'
	match 'update/award/assignment/:assignment_id/for/:child_id', :to => 'award_assignments#update'
	
	# for objective_assignments ajax
	match 'activate/objective/:objective_id/for/:child_id', :to => 'objective_assignments#activate'
	match 'deactivate/objective/assignment/:assignment_id/for/:child_id', :to => 'objective_assignments#deactivate'
	match 'update/objective/assignment/:assignment_id/for/:child_id', :to => 'objective_assignments#update'

	# for lesson_assignments ajax
	match 'update/lesson/assignment/:lesson_id/for/:child_id', :to => 'lesson_assignments#update'


	match 'requested/objective/:objective_id/for/:child_id', :to => 'objective_assignments#requested'
	match 'unrequested/objective/assignment/:assignment_id/for/:child_id', :to => 'objective_assignments#unrequested'
	
	match 'require_confirmation/assignment/:assignment_id/for/:child_id', :to => 'objective_assignments#require_confirmation'
	match 'remove_confirmation/assignment/:assignment_id/for/:child_id',  :to => 'objective_assignments#remove_confirmation'
	
	match 'check_name/:name', :to => 'users#check_name'
	
	match '/admin/' => 'admin#index', :as => :admin_index

	match '/blog/archive/(:year/(:month))', :to => 'blog#index'
	
	match '/forgot' => 'users#forgot_password', :as => 'forgot'
	
	match '/home' => 'users#home', :as => 'home'
	match '/invitation/:code' => 'invitations#accept_invite', :as => 'invitation'
	match '/logout' => 'sessions#destroy', :as => 'logout'
	match '/login' => 'sessions#new', :as => 'login'
	match '/register' => 'sessions#register', :as => 'register'
	match '/reset' => 'users#reset_password', :as => 'reset'
	match '/activate/:token' => 'users#activate', :as => 'activate'
	match '/resend' => 'users#resend', :as => 'resend'
	match '/amazon/(:index/(:term))' => 'amazon#search', :as => 'amazon'
	match "/:permalink", :to => 'static_pages#show'
	
	
	
end

app/views/shared/_analytics.html.haml
<script type="text/javascript">

var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-20980116-1']);
_gaq.push(['_trackPageview']);

(function() {
var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();

</script>

app/views/shared/_app_header.html.haml
#hd
	#logo
		-if @current_user.anonymous?
			= link_to image_tag( "logo.png", :alt=> "The Cherry Tree", :class => 'logo' ), root_path 
		-else 
			= link_to image_tag( "logo.png", :alt=> "The Cherry Tree", :class => 'logo' ), home_path 
	.nav
		-unless @current_user.child?
			= link_to "Resources", resources_path, :class=> 'button red'
			= link_to "Store", store_index_path, :class=> 'button red'
			=# link_to "Forums", forums_path, :class=> 'button_small blue'
	.user_capsule
		- if @current_user.anonymous?
			.loggedout
				= link_to "Login", login_path
				|
				= link_to "Register", register_path
		- else
			- unless avatar_tag( @current_user ).match(/gravatar.com/) #Only allow uploaded pics, no generic gravatar icons
				.pic
					= avatar_tag( @current_user, :thumb, :width => 36 )
			.user
				Logged in as:
				= link_to @current_user.display_name, home_path
				(
				= link_to "Logout", logout_path
				)
				%br
				%span
					=# link_to "Help", '/help'
					= link_to "Settings", settings_users_path
					|
					= link_to "Note Box", notes_path
					- if @current_user.note_deliveries.unread.count > 0
						.note_alert
							= link_to @current_user.note_deliveries.unread.count, notes_path

app/views/shared/_award_messages.html.haml
#award_message
	#text_container
		= award_message.html_safe

app/views/shared/_flash.html.haml
- unless flash.empty?
	#flash
		- flash.each do |key, value|
			- next if key == :award_message
			%div{ :class => key }
				= value.html_safe

app/views/shared/_footer.html.haml
#ft
	.copyright
		&copy; #{Time.now.year} CherryTree, LLC
	.footer_menu
		%li= link_to "About Us", "/about"
		%li= link_to "Privacy Policy", "/privacy"
		%li= link_to "Terms", "/terms"
		%li= link_to "Contact", new_contact_path
		- if @current_user.anonymous?
			%li= link_to "Admin", login_path
		- else
			%li
				Logged In As: 
				= @current_user.display_name
				| 
				= link_to "Logout", logout_path
	%br.clear

	

app/views/shared/_header.html.haml
#hd
	= link_to image_tag( "logo.png", :alt=> "The Cherry Tree", :id => 'logo', :class => 'logo' ), root_path
	.nav
		= link_to "Our Blog", blog_index_path, :class => 'red_button pop'
		= link_to "Contact Us", new_contact_path, :class => 'blue_button pop'

app/views/shared/_home_header.html.haml
#hd
	#logo
		= link_to image_tag( "logo.png", :alt=> "The Cherry Tree", :class => 'logo' ), root_path
	.nav
		= link_to "Resources", resources_path, :class=> 'button red'
		= link_to "Store", store_index_path, :class=> 'button red'
	.user_capsule
		- if @current_user.anonymous?
			.loggedout
				= link_to "Login", login_path
				|
				= link_to "Register", register_path
		- else
			.pic
				= avatar_tag( @current_user, :thumb, :width => 36 )
			Logged in as:
			= link_to @current_user.display_name, home_path
			%br
			= link_to "Logout", logout_path
			|
			= link_to "Settings", settings_users_path

app/views/shared/_sharing_widgets.html.erb
<script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "ur-5051c0dc-62e2-c887-c80e-c1bb8095f58c"}); </script>

<span class='st_facebook' displayText='Facebook'></span>
<span class='st_twitter' displayText='Tweet'></span>
<span class='st_email' displayText='Email'></span>
<span class='st_sharethis' displayText='ShareThis'></span>

app/views/shared/_treasure_item.html.haml
- for assignment in @current_user.award_assignments.active
            .treasure_box.clearfix
                = link_to image_tag( 'treasure_chest.png' ), awards_path
                .col
                    = link_to 'Go to Treasure Chest', awards_path
            .treasure_item
                %b= snip assignment.award.name, 20
                .item
                    = link_to avatar_tag( assignment.award, :thumb ), asdsa_path( assignment.award, :type => 'award' )
                .cost
                    Cost:
                    = assignment.point_cost
                    cherries
                - if assignment.point_cost > @current_user.point_balance
                    = assignment.point_cost - @current_user.point_balance
                    cherries to Go!
                    %p
                    = raw(Gchart.bar(:data => [[@current_user.point_balance],[assignment.point_cost]], :stacked => true, :bar_colors =>'00FF00,FF0000', :orientation => 'horizontal', :size => '100x20', :custom=>'chxt=y,x&chxs=0,,0,0,_,676767|1,,0,0,_,676767&chf=bg,s,67676700&chf=bg,s,67676700', :format=>'image_tag' ))
                - else
                    = link_to "Unlock It!", asda_path( assignment.award, :type => 'award'), :class => 'button_small red'
                
        .clear