config/routes.rb
CherryTree::Application.routes.draw do

	root :to => "site#index"
	
	resources :activities do
		resources :comments
	end
	
	resources :articles do
		resources :comments
	end
	
	resources :awards do
		get 'admin', :on => :collection
		get 'unlock', :on => :member
		get 'earned', :on => :collection
		get 'set', :on => :collection
		get 'print', :on => :member
	end
	
	resources :blog do
		get	:admin, :on => :collection
	end
	
	resources :checkins do
		post 'pokki_create', :on => :collection
	end
	
	resources :lessons do
		resources :screens
	end
	
	resources :children do
		get 'login', :on => :collection
		get 'home', :on => :collection
		get 'profile', :on => :member
		post 'give_cherries', :on => :member
				
		resources :approvals

		resources :objective_assignments do
			get 'pokki', :on => :collection
		end
		
		resources :award_assignments do
			post 'amzn', :on => :collection
		end
		resources :lesson_assignments
		resources :lessons
		
		resources :journal_entries do
			resources :comments
			get 'customize', :on => :member
		end
		resources :invitations
		
		resources :supporters do
			get 'disable', :on => :collection
			get 'enable', :on => :collection
		end
	end

	resources :contacts do
		get 'admin', :on  => :collection
	end
	
	resources :forums do
		resources :topics do
			resources :posts
		end
	end
	
	resources :games
	
	resources :guides
	
	resources :invitations

	resources :merches
	
	resources :store
	
	resources :notes do
		get 'archive', :on => :collection
		get 'customize', :on => :member
	end
	
	resources :objectives 
		
	resources :products
	
	resources :quizzes do
		get 'admin', :on => :collection
		get 'inspect', :on => :member
		get 'recap', :on => :member
		resources :questions do
			get 'admin', :on => :collection
			post 'answer', :on => :member
			resources :answers do
				get 'admin', :on => :collection
			end
		end
	end
	
	resources :relations
	
	resources :sessions do
		collection do
			get 'pending'
			get 'register'
			get 'register_invitee'
			post 'go_facebook'
			post 'go_site_facebook'
			get 'ret_facebook'
			get 'ret_site_facebook'
			post 'go_twitter'
			post 'go_site_twitter'
			get 'ret_twitter'
			get 'ret_site_twitter'
			post 'json_create'
		end
	end
	
	resources :static_pages do
		get 'admin', :on => :collection
	end
	
	resources :page_elements do
		get 'update_pos', :on => :member
		get 'update_width', :on => :member
	end
	
	resources :resources
	
	resources  :users do
		post 'collect_email', :on => :collection
		get 'resend', :on => :member
		get 'settings', :on => :collection
		get 'home', :on => :collection
		post 'invite', :on => :collection
		resources :photos
	end
	
	resources :weekly_approvals
	
	resources :wishlist_items
	
	match '/update_page/:obj_type/:obj_id', :to => 'page_elements#updater'
	
	# for award_assignments ajax
	match 'activate/award/:award_id/for/:child_id', :to => 'award_assignments#activate'
	match 'deactivate/award/assignment/:assignment_id/for/:child_id', :to => 'award_assignments#deactivate'
	match 'update/award/assignment/:assignment_id/for/:child_id', :to => 'award_assignments#update'
	
	# for objective_assignments ajax
	match 'activate/objective/:objective_id/for/:child_id', :to => 'objective_assignments#activate'
	match 'deactivate/objective/assignment/:assignment_id/for/:child_id', :to => 'objective_assignments#deactivate'
	match 'update/objective/assignment/:assignment_id/for/:child_id', :to => 'objective_assignments#update'

	# for lesson_assignments ajax
	match 'update/lesson/assignment/:lesson_id/for/:child_id', :to => 'lesson_assignments#update'


	match 'requested/objective/:objective_id/for/:child_id', :to => 'objective_assignments#requested'
	match 'unrequested/objective/assignment/:assignment_id/for/:child_id', :to => 'objective_assignments#unrequested'
	
	match 'require_confirmation/assignment/:assignment_id/for/:child_id', :to => 'objective_assignments#require_confirmation'
	match 'remove_confirmation/assignment/:assignment_id/for/:child_id',  :to => 'objective_assignments#remove_confirmation'
	
	match 'check_name/:name', :to => 'users#check_name'
	
	match '/admin/' => 'admin#index', :as => :admin_index

	match '/blog/archive/(:year/(:month))', :to => 'blog#index'
	
	match '/forgot' => 'users#forgot_password', :as => 'forgot'
	
	match '/home' => 'users#home', :as => 'home'
	match '/invitation/:code' => 'invitations#accept_invite', :as => 'invitation'
	match '/logout' => 'sessions#destroy', :as => 'logout'
	match '/login' => 'sessions#new', :as => 'login'
	match '/register' => 'sessions#register', :as => 'register'
	match '/reset' => 'users#reset_password', :as => 'reset'
	match '/activate/:token' => 'users#activate', :as => 'activate'
	match '/resend' => 'users#resend', :as => 'resend'
	match '/amazon/(:index/(:term))' => 'amazon#search', :as => 'amazon'
	match "/:permalink", :to => 'static_pages#show'
	
	
	
end

app/models/award.rb
# == Schema Information
# Schema version: 20110420185439
#
# Table name: awards
#
#  id                :integer(4)      not null, primary key
#  creator_id        :integer(4)
#  creator_type      :string(255)
#  award_category_id :integer(4)
#  name              :string(255)
#  description       :text
#  asin              :string(255)
#  point_cost        :integer(4)
#  status            :string(255)     default("active")
#  created_at        :datetime
#  updated_at        :datetime
#

class Award < ActiveRecord::Base
	
	# after_create :set_avatar
	belongs_to	:award_category
	belongs_to	:creator, :polymorphic => true
	has_many	:ownings, :as => :ownable
	
	has_many	:users, :through => :ownings
	
	has_many	:award_assignments
	has_many	:assigned_users, :through => :award_assignments, :class_name => 'User', :source => :user
	
	has_attached	:avatar
	
	scope :amazon, where( 'asin is not null' )
	scope :coupon, where( 'asin is null' )
	
	
	def award_type
		return self.asin.present? ? 'product' : 'coupon'
	end
	
	def available_to?( user )
		self.assigned_users.include?( user )
	end
	
	def assignment_for( user )
		return self.award_assignments.where( :user_id => user.id ).first
	end
	
	def self.create_from_amazon( award )
		result = Amazon::Ecs.item_search( award[:asin], :response_group => 'Medium', :search_index => award[:index] ).items.first
		if result.nil?
			return "didn't find product for asin #{asin}"
		end
		
		award = Award.new( :name => result.get('ItemAttributes/Title'), :description => result.get('EditorialReviews/EditorialReview/Content'), :asin =>award[:asin], :url => result.get('DetailPageURL') )
		#award.point_cost = result.get('OfferSummary/LowestNewPrice/FormattedPrice').gsub( /\D/, "" ).to_i.roundup
		award.point_cost = 50
		if award.save
			avatar = Attachment.create_from_resource( result.get_hash( 'MediumImage' )['URL'], 'avatar', :owner => award, :remote => 'true' )
			return award
		else
			return "couldn't save reward"
		end
	end
	
	private
	
	def set_avatar
		if self.avatar.nil?
			pic = Attachment.create( :path => '/images/trophy.png', :name => 'trophy', :attachment_type => 'avatar', :owner => self, :format => 'png', :remote => true )
		end
	end
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
	#before_filter	:require_admin, :except => [ :index, :show ]
	
	def admin
		@awards = Award.all
	end
	
	def index
		if @current_user.child?
			# so far, this is only used for the child's treasure chest
			@award_assignments = @current_user.award_assignments
			@fonts = Font.all
			@stickers = Sticker.all
			@backgrounds = Background.all
			render 'index_child'
		else
			# todo -- move awards/new to here?
			redirect_to new_award_path
		end
		
	end
	
	def print
		@award = Award.find params[:id]
		@child = Child.find params[:child_id]
		owning = @child.ownings.find_by_ownable_id_and_ownable_type( @award.id, 'Award' )
		@cert_number = "000#{owning.id}"
		render :show, :layout => 'certificate'
	end
	
	def earned
		@unlockables = @current_user.unlockables
		@awards = @current_user.awards
		@achievements = @current_user.achievement_earnings
	end
	
	def show
		@award = Award.find params[:id]

	end
	
	def new
		@award = Award.new
	end
	
	def edit
		@award = Award.find params[:id]
	end
	
	def unlock
		@award = eval "#{params[:type].capitalize}.find( params[:id] )"
		success, msg = @current_user.unlock( @award )
		if success
			pop_flash "Congratulations, ask your <br>parent to check their email <br>for your prize!", :award_message
			@current_user.do_activity( "Unlocked the award: '#{@award.name}'!", @award )
			redirect_to print_award_url( @award, :child_id => @current_user.id, :host => request.host )
		else
			pop_flash msg, :error
			redirect_to :back
			
		end
	end

	def create
		if params[:award][:asin]
			@award = Award.create_from_amazon( params[:award] )
		else
			@award = Award.new params[:award]
		end
		
		@award.update_attributes :creator_id => @current_user.id, :creator_type => @current_user.class.name
		
		if @award.save
			process_attachments_for( @award )
			pop_flash "award Created"
		else
			pop_flash "Oooops, award not saved", :error, @award
		end
		redirect_to new_award_path
	end
	
	def update
		@award = Award.find params[:id]
		if @award.update_attributes params[:award]
			process_attachments_for( @award )
			pop_flash "award Updated"
		else
			pop_flash "Oooops, award not saved", :error, @award
		end
		redirect_to :back
	end
	
	
		
end

app/views/awards/_amazon_form.html.haml
.form_group
	= form_tag amazon_path do 
		Search Amazon:
		= text_field_tag :term
		For:
		= select_tag :index, options_for_select( ['Apparel', 'Books', 'DVD', 'Electronics', 'Toys', 'HealthPersonalCare', 'Kitchen', 'Music', 'DigitalMusic', 'SportingGoods', 'Video', 'VideoGames' ], 'Toys' )
		= submit_tag "Search", :class => 'button'
%br

app/views/awards/_form.html.haml
.form_group
	= f.label 'Title:'
	= f.text_field :name
	= f.label 'Text:'
	= f.text_area :description, :class => 'tiny_area'
	= f.submit

app/views/awards/earned.html.haml
-# The Treasure Chest
= render 'children/banner', :title => 'Objectives'
= render 'children/nav'

%h3 Your Achievements
- for achievement in @achievements
	%li
		= achievement.achievement.name
		on
		= format_date_only achievement.created_at


%h3 Your Prizes
- for awarding in @awards
	.listing
		.listing_avatar
			= avatar_tag( awarding.ownable, :thumb, :width => 64 )
		%b= awarding.ownable.name
		= awarding.ownable.description
		Unlocked on
		= format_date_only awarding.created_at
	.clear
	%hr

- for unlocking in @unlockables
	.listing
		.listing_avatar
			= avatar_tag( unlocking.ownable, :thumb, :width => 64 )
		%b= unlocking.ownable.name
		= unlocking.ownable.description
		= format_date_only unlocking.created_at
	.clear
	%hr

app/views/awards/edit.html.haml
%h3 Edit Reward
= form_for @award, :html => { :multipart => true }  do |f|
	= render 'form', :f => f

app/views/awards/index_child.html.haml
-# The Treasure Chest

- unless @award_assignments.empty?
	#awards
		%h3 Pick a prize!

		- for assignment in @award_assignments.active
			.treasure_item
				%b= snip assignment.award.name, 20
				.item
					= link_to avatar_tag( assignment.award, :thumb ), unlock_award_path( assignment.award, :type => 'award' )
				.cost
					Cost:
					= assignment.point_cost
					cherries
				- if assignment.point_cost > @current_user.point_balance
					= assignment.point_cost - @current_user.point_balance
					cherries to Go!
					.chart
						= raw(Gchart.bar(:data => [[@current_user.point_balance],[assignment.point_cost]], :stacked => true, :bar_colors =>'00FF00,FF0000', :orientation => 'horizontal', :size => '100x20', :custom=>'chxt=y,x&chxs=0,,0,0,_,676767|1,,0,0,_,676767&chf=bg,s,67676700&chf=bg,s,67676700', :format=>'image_tag' ))
				- else
					= link_to "Unlock It!", unlock_award_path( assignment.award, :type => 'award'), :class => 'button_small red'
				
		%br.clear

app/views/awards/new.html.haml
%h1
	= possessize @current_user.name
	Rewards
= render 'users/nav'

%h2 New Reward

%h4 Your Rewards:
- for award in @current_user.created_awards.amazon
	%li= award.name
	
Search Amazon
= render 'amazon_form'



%p
	Wishlists
	
%h4 Your Coupons:
- for award in @current_user.created_awards.coupon
	%li= award.name

Create Coupon
= form_for Award.new do |f|
	= render 'form', :f => f

app/views/awards/search_amazon.html.haml
	.amzn_confirm
		= form_for Award.new do |f|
			= f.hidden_field :asin, :value => item.get('asin')
			= f.hidden_field :search_index, :value => @search_index
			= f.submit "Yeah, Add it!"
	.clear
	%hr

app/views/awards/set.html.haml
%h1 Add Rewards
= render 'users/nav'
%br
%h3 Add an reward from Amazon
=render 'awards/amazon_form'

#wishitems
	-for child in @current_user.children
		%h3 
			Add an reward from  
			= possessize child.display_name
			Wishlist items
	
		.form_group
			= form_for @award=Award.new, :html => { :multipart => true } do |f|

				%br
				= f.submit "Enter", :class => 'button'

app/views/awards/show.html.haml
- unless current_page?( print_award_path )
	.float_right{ :style => 'margin-bottom:10px;' }
		= link_to 'Print', print_award_path( @award, :child_id => 4 ), :class => 'button green', :target => '_new' 
	%br.clear

<a href="javascript:window.print()">Print</a>
| 
=link_to "Return", home_url

#award_certificate
	#award-tree
		= image_tag( 'certificate-tree.png' )
	#award_logo
		= image_tag 'logo.png'
	#award_name= @award.name
	
	#child_name
		Awarded To:
		= @child.display_name.capitalize
	
	#award_text.center
		This award hereby certifies that
		%p
			%h2= @child.display_name.capitalize
		has earned the following: 
		%p
			%h3= @award.name

	
	#award_date
		Hereby acknowledged this
		%b= Time.now.day.ordinalize
		day of
		= "<b>#{Time.now.strftime("%B")}</b>, in the year".html_safe
		%b= Time.now.year
		%br
		%br
		%br
		By:
		
	#award_cert
		CherryTree Certificate Number:
		= @cert_number
		