config/routes.rb
CherryTree::Application.routes.draw do

	root :to => "site#index"
	
	resources :activities do
		resources :comments
	end
	
	resources :articles do
		resources :comments
	end
	
	resources :awards do
		get 'admin', :on => :collection
		get 'unlock', :on => :member
		get 'earned', :on => :collection
		get 'set', :on => :collection
		get 'print', :on => :member
	end
	
	resources :blog do
		get	:admin, :on => :collection
	end
	
	resources :checkins do
		post 'pokki_create', :on => :collection
	end
	
	resources :lessons do
		resources :screens
	end
	
	resources :children do
		get 'login', :on => :collection
		get 'home', :on => :collection
		get 'profile', :on => :member
		post 'give_cherries', :on => :member
				
		resources :approvals

		resources :objective_assignments do
			get 'pokki', :on => :collection
		end
		
		resources :award_assignments do
			post 'amzn', :on => :collection
		end
		resources :lesson_assignments
		resources :lessons
		
		resources :journal_entries do
			resources :comments
			get 'customize', :on => :member
		end
		resources :invitations
		
		resources :supporters do
			get 'disable', :on => :collection
			get 'enable', :on => :collection
		end
	end

	resources :contacts do
		get 'admin', :on  => :collection
	end
	
	resources :forums do
		resources :topics do
			resources :posts
		end
	end
	
	resources :games
	
	resources :guides
	
	resources :invitations

	resources :merches
	
	resources :store
	
	resources :notes do
		get 'archive', :on => :collection
		get 'customize', :on => :member
	end
	
	resources :objectives 
		
	resources :products
	
	resources :quizzes do
		get 'admin', :on => :collection
		get 'inspect', :on => :member
		get 'recap', :on => :member
		resources :questions do
			get 'admin', :on => :collection
			post 'answer', :on => :member
			resources :answers do
				get 'admin', :on => :collection
			end
		end
	end
	
	resources :relations
	
	resources :sessions do
		collection do
			get 'pending'
			get 'register'
			get 'register_invitee'
			post 'go_facebook'
			post 'go_site_facebook'
			get 'ret_facebook'
			get 'ret_site_facebook'
			post 'go_twitter'
			post 'go_site_twitter'
			get 'ret_twitter'
			get 'ret_site_twitter'
			post 'json_create'
		end
	end
	
	resources :static_pages do
		get 'admin', :on => :collection
	end
	
	resources :page_elements do
		get 'update_pos', :on => :member
		get 'update_width', :on => :member
	end
	
	resources :resources
	
	resources  :users do
		post 'collect_email', :on => :collection
		get 'resend', :on => :member
		get 'settings', :on => :collection
		get 'home', :on => :collection
		post 'invite', :on => :collection
		resources :photos
	end
	
	resources :weekly_approvals
	
	resources :wishlist_items
	
	match '/update_page/:obj_type/:obj_id', :to => 'page_elements#updater'
	
	# for award_assignments ajax
	match 'activate/award/:award_id/for/:child_id', :to => 'award_assignments#activate'
	match 'deactivate/award/assignment/:assignment_id/for/:child_id', :to => 'award_assignments#deactivate'
	match 'update/award/assignment/:assignment_id/for/:child_id', :to => 'award_assignments#update'
	
	# for objective_assignments ajax
	match 'activate/objective/:objective_id/for/:child_id', :to => 'objective_assignments#activate'
	match 'deactivate/objective/assignment/:assignment_id/for/:child_id', :to => 'objective_assignments#deactivate'
	match 'update/objective/assignment/:assignment_id/for/:child_id', :to => 'objective_assignments#update'

	# for lesson_assignments ajax
	match 'update/lesson/assignment/:lesson_id/for/:child_id', :to => 'lesson_assignments#update'


	match 'requested/objective/:objective_id/for/:child_id', :to => 'objective_assignments#requested'
	match 'unrequested/objective/assignment/:assignment_id/for/:child_id', :to => 'objective_assignments#unrequested'
	
	match 'require_confirmation/assignment/:assignment_id/for/:child_id', :to => 'objective_assignments#require_confirmation'
	match 'remove_confirmation/assignment/:assignment_id/for/:child_id',  :to => 'objective_assignments#remove_confirmation'
	
	match 'check_name/:name', :to => 'users#check_name'
	
	match '/admin/' => 'admin#index', :as => :admin_index

	match '/blog/archive/(:year/(:month))', :to => 'blog#index'
	
	match '/forgot' => 'users#forgot_password', :as => 'forgot'
	
	match '/home' => 'users#home', :as => 'home'
	match '/invitation/:code' => 'invitations#accept_invite', :as => 'invitation'
	match '/logout' => 'sessions#destroy', :as => 'logout'
	match '/login' => 'sessions#new', :as => 'login'
	match '/register' => 'sessions#register', :as => 'register'
	match '/reset' => 'users#reset_password', :as => 'reset'
	match '/activate/:token' => 'users#activate', :as => 'activate'
	match '/resend' => 'users#resend', :as => 'resend'
	match '/amazon/(:index/(:term))' => 'amazon#search', :as => 'amazon'
	match "/:permalink", :to => 'static_pages#show'
	
	
	
end

app/models/lesson_assignment.rb
# == Schema Information
# Schema version: 20110420185439
#
# Table name: lesson_assignments
#
#  id          :integer(4)      not null, primary key
#  user_id     :integer(4)
#  lesson_id   :integer(4)
#  creator_id  :integer(4)
#  point_value :integer(4)      default(1)
#  status      :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class LessonAssignment < ActiveRecord::Base
	belongs_to	:user
	belongs_to	:lesson
	scope :active, where( "status = 'active'" )
	
	def completed_by?( user )
		#Completed by means that the quizzing for the lesson has a 'complete' status
		if self.lesson.quizzes.present? && quizzing = self.lesson.quizzes.last.quizzings.where("user_id = ?", self.user_id).last #Some lessons don't have quizzes
			if quizzing.present? && quizzing.status == 'complete'
				return true
			else
				return false
			end
		else
			return false
		end
	end
	
	def offered_today_to?( user )
		return false unless self.lesson.lesson_viewings.find_by_user_id( user ).present?
		self.lesson.lesson_viewings.find_by_user_id( user.id ).updated_at > Time.now.beginning_of_day
	end
	
end

app/controllers/lesson_assignments_controller.rb
class LessonAssignmentsController < ApplicationController
	before_filter :get_child
	
	def create
		unless @child.parents.include?( @current_user )
			pop_flash "Access Denied", :error
			redirect_to :back
			return false
		end
		
		lesson = Lesson.find( params[:lesson_id] )
		@child.lesson_assignments.create :lesson => lesson, :creator_id => @current_user.id
		
		redirect_to :back
		
		
	end
	
	def update
		@assignment = LessonAssignment.find( params[:lesson_id] )
		@assignment.update_attributes :status => params[:status]
		redirect_to :back
	end
	
	def index
		if @current_user.is_child?
			@assignments = @current_user.lesson_assignments
			render :child_index
		else
			unless @child.parents.include?( @current_user ) || @current_user == @child
				pop_flash "Access Denied", :error
				redirect_to :back
				return false
			end
			@lessons = Lesson.all
			@quizzes = Quiz.standalone
			
			#@new_assignment = @child.lesson_assignments.new [TODO: Think this is unnecesary, delete on cleanup]
			@assignments = @child.lesson_assignments
			
			render :adult_index
			
		end
	end
	
	
	private
	
	def get_child
		@child = Child.find( params[:child_id] )
	end
	
end

app/views/lesson_assignments/_lesson_assignment.html.haml
Do you want to take the lesson:
= lesson_assignment.lesson.name
?
%br
= lesson_assignment.lesson.description
%br
= link_to "Yes", lesson_screen_path( lesson_assignment.lesson, lesson_assignment.lesson.screens.first ), :class => 'button green'

= link_to "Not Now", home_path, :class => 'button red'

app/views/lesson_assignments/_lesson_assignment_table.html.haml
%div[assignment]
	.float_left{ :style => 'width:50px;'}
		= check_box_tag 'unassign_lesson', assignment.lesson.id, true, :lesson => assignment.lesson.id, :class => 'unassign_lesson', :child => @child.id, :assignment => assignment.id, :status => 'inactive'

	.float_left{ :style => 'width:400px;'}
		= assignment.lesson.name

	.float_left{ :style => 'width:150px;' } 
		= text_field_tag :objective_points, assignment.point_value, :id => "lesson_assignment_#{assignment.id}", :class => "lesson_points", :style => 'width:100px;', :child => @child.id, :assignment => assignment.id
	.clear

app/views/lesson_assignments/adult_index.html.haml
.child_profile

	= render 'children/sub_nav', :child => @child
	%br.clear

	- if @assignments.active.empty?
		%p
		= @child.display_name
		does not have any activities yet.
		You can add an activity from the list below.
	- else
		#active_assignment_table_header{ :style => 'margin-top:20px;' }
			.float_left
				%h3 
					%span<= @child.display_name
					%span>'s Assigned Activities
			.clear
		#active_assignment_table_body
			%br
			.float_left{ :style => 'width:50px;'}
				&nbsp;
			.float_left{ :style => 'width:400px;'}
				%h4 Assigned Activites
			.float_left{ :style => 'width:150px;'}
				%h4 Cherries
			.clear
			- for assignment in @assignments.active
				= render 'lesson_assignment_table', :assignment => assignment

	%br.clear
	.new_thing.button_flat
		= link_to "Save Changes", child_path( @child )
	%br
	.top-header.clearfix
		%span.title
	
		-#.new_thing.button_flat
			= link_to 'Buy Lessons!', ""
	#accordion.goals	
		- for category in LessonCategory.order("sequence")
			-next if category.lessons.empty?
			%h3.track= "#{category.name}"
			%div
				%ul
					- for lesson in category.lessons
						%li
							%h4
								="#{lesson.name} (#{lesson.lesson_type})"
							- if lesson.lesson_assignments.find_by_user_id( @child.id ) && lesson.lesson_assignments.find_by_user_id( @child.id ).completed_by?( @child )
								Completed on:
								= format_date_only lesson.lesson_viewings.find_by_user_id( @child.id ).updated_at
							- elsif lesson.lesson_viewings.find_by_user_id( @child.id ) && lesson.lesson_viewings.find_by_user_id( @child.id ).screen_id > 0
								Started on:
								= format_date_only lesson.lesson_viewings.find_by_user_id( @child.id ).created_at
								-
							- else
								= @child.display_name
								hasn't started yet - 	
							.blue_link
								- if @child.lessons.include?( lesson ) && lesson.lesson_assignments.find_by_user_id( @child.id ).completed_by?( @child )
									= link_to 'Reassign', child_lesson_assignment_path( @child, lesson, :status => 'active' ), :method => :put
								- elsif @child.lessons.include?( lesson )
									= link_to 'Unassign', child_lesson_assignment_path( @child, lesson, :status => 'inactive' ), :method => :put
								- else
									= link_to 'Assign', child_lesson_assignments_path( @child, :lesson_id => lesson.id ), :method => :post
									|
									= link_to 'View', child_lesson_path( @child, :id => lesson.id )

%br.clear
.new_thing.button_flat
	= link_to "Save Changes", child_path( @child ), :class => 'save_form'
%br

app/views/lesson_assignments/child_index.html.haml
.objective_dash.clearfix
	- if @assignments.present?
		%h3 Activities
	- else
		%h3 No Lessons or Activities

	%table( width = 600 )
		%th
			%b Name
		%th
			%b Cherries
		%th
			%b Action
		- for assignment in @assignments
			-unless assignment.lesson.quizzes.first.taken_by?( @current_user )
				%tr
					%td
						= assignment.lesson.name
					%td
						= assignment.lesson.quizzes.first.point_value
					%td
						= link_to "Take It", lesson_screen_path( assignment.lesson, assignment.lesson.screens.first )
%br.clear
%br

app/views/lesson_assignments/index.html.haml
.child_profile

	= render 'children/sub_nav', :child => @child
	
	.top-header.clearfix
		%span.title
			Assign lessons and activities here.
	
		.new_thing.button_flat
			= link_to 'Buy Lessons!', ""

	%table( width = 600 )
		%th
			%b Name
		%th
			%b Status
		%th
			%b Activate
		- for lesson in @lessons
			%tr
				%td= lesson.name
				%td
					- if lesson.lesson_assignments.find_by_user_id( @child.id ) && lesson.lesson_assignments.find_by_user_id( @child.id ).completed_by?( @child )
						Completed on:
						= format_date_only lesson.lesson_viewings.find_by_user_id( @child.id ).updated_at
					- elsif lesson.lesson_viewings.find_by_user_id( @child.id ) && lesson.lesson_viewings.find_by_user_id( @child.id ).screen_id > 0
						Started on:
						= format_date_only lesson.lesson_viewings.find_by_user_id( @child.id ).created_at
					- else
						Not Viewed
				%td
					- if @child.lessons.include? ( lesson )
						= link_to 'Unassign', child_lesson_assignment_path( @child, lesson, :status => 'inactive' ), :method => :put
					- else
						= link_to 'Assign', child_lesson_assignments_path( @child, :lesson_id => lesson.id ), :method => :post

%br.clear
%br